Repository qri-io/frontend, pull requests merged in 2019-05, with the labels that each got.

#487 fix(pagination): fixes pagination on datasets, registry datasets, profiles, search results, and history
  lib/actions/app.js
  lib/actions/dataset.js
  lib/components/App.js
  lib/components/Collection.js
  lib/components/Datasets.js
  lib/components/List.js
  lib/components/Network.js
  lib/components/SearchResults.js
  lib/components/dataset/Commits.js
  lib/constants/app.js
  lib/containers/App.js
  lib/containers/Collection.js
  lib/containers/Commits.js
  lib/containers/Network.js
  lib/containers/SearchResults.js
  lib/reducers/__tests__/app.test.js
  lib/reducers/app.js
  lib/selectors/registry.js
Labels: in progress

#490 feat(dataset): add pagination to the body
  .babelrc
  lib/actions/body.js
  lib/actions/dataset.js
  lib/actions/editor.js
  lib/components/chrome/LoadMore.js
  lib/components/dataset/Body.js
  lib/components/dataset/Dataset.js
  lib/components/dataset/DatasetRouter.js
  lib/constants/body.js
  lib/containers/Dataset.js
  lib/middleware/extractBody.js
  lib/reducers/__tests__/body.test.js
  lib/reducers/body.js
  lib/reducers/index.js
  lib/reducers/pagination.js
  lib/schemas.js
  lib/scss/_chrome.scss
  lib/scss/_dataset.scss
  lib/scss/_handsontable.scss
  lib/selectors/dataset.js
  lib/store/configureStore.dev.js
  lib/store/configureStore.prod.js
  package.json
  yarn.lock
Labels: feat, perf, ui

#491 copy: Adjust some instructions on forking
  DEVELOPER.md
Labels: docs
