Repository qri-io/frontend, pull requests merged in 2019-06, with the labels that each got.

#496 fix(StructureForm): make json-schema link an ExternalLink
  lib/components/form/StructureForm.js
Labels: bug

#497 link and typo fixes
  readme.md
Labels: docs

#494 Use valid monospace font name
  lib/scss/_site.scss
Labels: bug, ui

#508 fix(styles): add custom webpack file to storybook config to load scss
  .storybook/webpack.config.js
  stories/index.js
  yarn.lock
Labels: fix

#509 refactor(DownloadBar): add DownloadBar to dataset page in READONLY mode
  .storybook/webpack.config.js
  lib/components/chrome/DownloadBar.js
  lib/components/dataset/Dataset.js
  lib/scss/_buttons.scss
  lib/scss/_chrome.scss
  stories/index.js
Labels: enhancement

#511 chore(release): release v0.7.2
  CHANGELOG.md
  package.json
  version.js
Labels: chore
