Repository qri-io/frontend, pull requests merged in 2021-09, with the labels that each got.

#322 refactor: extended versionInfo interface…
  src/features/dataset/DatasetFixedLayout.tsx
  src/features/dataset/DatasetHeader.tsx
  src/features/dataset/DatasetNavSidebar.tsx
  src/features/dataset/DatasetRoutes.tsx
  src/features/dataset/DatasetScrollLayout.tsx
  src/features/dataset/state/datasetActions.ts
  src/features/dataset/state/datasetState.ts
  src/qri/versionInfo.ts
Labels: refactor

#332 feat(Icon): add `Unlock` icon & use it in `DatasetHeader`
  src/chrome/Icon.tsx
  src/chrome/icon/Unlock.tsx
  src/features/dataset/DatasetHeader.tsx
Labels: feat

#329 fix(trigger): cron trigger must start sometime after first deploy
  src/features/deploy/state/deployActions.ts
  src/features/trigger/util.ts
  src/features/workflow/utils/prepareWorkflowForDeploy.ts
Labels: fix

#341 refactor(workflow): `WorkflowHeading` => `WorkflowHeader`
  src/features/workflow/Workflow.tsx
  src/features/workflow/WorkflowCell.tsx
  src/features/workflow/WorkflowHeader.tsx
  src/features/workflow/WorkflowOutline.tsx
  src/features/workflow/WorkflowScriptStatus.tsx
  src/features/workflow/WorkflowStepStatusCircle.tsx
  src/features/workflow/WorkfolwHeading.tsx
  src/features/workflow/state/workflowActions.ts
Labels: refactor

#345 feat(websocket): add authentication to websocket connection
  src/features/app/App.tsx
  src/features/app/modal/Modal.tsx
  src/features/commits/CommitSummaryHeader.tsx
  src/features/dataset/DatasetRoutes.tsx
  src/features/deploy/state/deployActions.ts
  src/features/dsPreview/state/dsPreviewActions.ts
  src/features/websocket/middleware/websocket.ts
  src/features/websocket/state/websocketActions.ts
  src/qri/events.ts
Labels: feat
